#!/usr/bin/env python3
import os
import sys

# Provenance line: Generated by software-requirements v4.0.0
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS_DIR = os.path.join(ROOT_DIR, 'docs')
OUT_DIR = os.path.join(ROOT_DIR, 'build', 'wiki')

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print("Generating wiki pages from docs/...")

    for fname in ['install.md', 'manual.md']:
        src_path = os.path.join(DOCS_DIR, fname)
        if os.path.exists(src_path):
            with open(src_path, 'r', encoding='utf-8') as f:
                content = f.read()
            out_path = os.path.join(OUT_DIR, fname)
            with open(out_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Generated: {out_path}")

    print("Wiki generation complete.")

if __name__ == '__main__':
    main()
